name: pusharound
description: "A client-side package for the pusharound protocol."
version: 0.0.1
homepage: https://github.com/getlantern/pusharound-flutter

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pushy_flutter: 2.0.18
  ttl_cache: 0.3.0
  provider: ^6.0.0 # Used by the example application

dev_dependencies:
  flutter_lints: ^3.0.1
  test: ^1.25.2

